### ISSUE TITLE
add "https://" when copy to clipboard

### ISSUE THREAD

**Issue by LLinoor** [vanajmoorthy/mcow.ml#10]
Hi,
I have a little problem when I copy the output link is that it only copies the link displayed without the "https://" before the link, which is annoying when I share the link with friends on Discord for example (because it doesn't detect it as a link). I tried to make a pull request by modifying the copy.js file but it was unsuccessful. So I checked the documentation of clipboard.js but I didn't understand anything. If you know how to do it can you do it please? Thanks in advance, have a nice day! :)

**Comment by vanajmoorthy** [comment]
Done sir :)
I had to implement a slightly hack solution but it works for now.
Thank you for pointing this out.

**Comment by LLinoor** [comment]
Thank you very much ! The project is really excellent thank you !! 😁

**Comment by vanajmoorthy** [comment]
I added a slightly better implementation if you want to check it out :)

**Comment by LLinoor** [comment]
It's beautiful, thank you very much !
